INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('AF','Afghanistan')
,('ZA','Afrique du Sud')
,('AX','Åland')
,('AL','Albanie')
,('DZ','Algérie')
,('DE','Allemagne')
,('DD','Allemagne de l''EST')
,('AD','Andorre')
,('AO','Angola')
,('AI','Anguilla')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('AQ','Antarctique')
,('AG','Antigua et Barbuda')
,('AN','Antilles néerlandaises')
,('SA','Arabie Saoudite')
,('AR','Argentine')
,('AM','Arménie')
,('AW','Aruba')
,('AU','Australie')
,('AT','Autriche')
,('AZ','Azerbaïdjan')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('BS','Bahamas')
,('BH','Bahrein')
,('BD','Bangladesh')
,('BB','Barbade')
,('BY','Bélarus')
,('BE','Belgique')
,('BZ','Bélize')
,('BJ','Bénin')
,('BM','Bermudes')
,('BT','Bhoutan')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('BO','Bolivie (État plurinational de)')
,('BQ','Bonaire')
,('BA','Bosnie-Herzégovine')
,('BW','Botswana')
,('BV','Bouvet')
,('BR','Brésil')
,('BN','Brunéi Darussalam')
,('BG','Bulgarie')
,('BF','Burkina Faso')
,('BI','Burundi')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('CV','Cabo Verde')
,('KY','Caïmans')
,('KH','Cambodge')
,('CM','Cameroun')
,('CA','Canada')
,('CL','Chili')
,('CN','Chine')
,('CX','Christmas')
,('CY','Chypre')
,('CC','Cocos/Keeling (Îles)')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('CO','Colombie')
,('KM','Comores')
,('CG','Congo')
,('CD','Congo')
,('CK','Cook')
,('KR','Corée')
,('KP','Corée')
,('CR','Costa Rica')
,('CI','Côte d''Ivoire')
,('HR','Croatie')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('CU','Cuba')
,('CW','Curaçao')
,('DK','Danemark')
,('DJ','Djibouti')
,('DO','Dominicaine')
,('DM','Dominique')
,('EG','Egypte')
,('SV','El Salvador')
,('AE','Emirats arabes unis')
,('EC','Equateur')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('ER','Erythrée')
,('ES','Espagne')
,('EE','Estonie')
,('US','Etats-Unis d''Amérique')
,('ET','Ethiopie')
,('FK','Falkland/Malouines (Îles)')
,('FO','Féroé')
,('FJ','Fidji')
,('FI','Finlande')
,('FR','France')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('GA','Gabon')
,('GM','Gambie')
,('GE','Géorgie')
,('GS','Géorgie du sud et les îles Sandwich du sud')
,('GH','Ghana')
,('GI','Gibraltar')
,('GR','Grèce')
,('GD','Grenade')
,('GL','Groenland')
,('GP','Guadeloupe')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('GU','Guam')
,('GT','Guatemala')
,('GG','Guernesey')
,('GN','Guinée')
,('GW','Guinée-Bissau')
,('GQ','Guinée équatoriale')
,('GY','Guyana')
,('GF','Guyane française')
,('HT','Haïti')
,('HM','Heard')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('HN','Honduras')
,('HK','Hong Kong')
,('HU','Hongrie')
,('IM','Île de Man')
,('UM','Îles mineures éloignées des Etats-Unis')
,('VG','Îles vierges britanniques')
,('VI','Îles vierges des Etats-Unis')
,('IN','Inde')
,('IO','Indien (Territoire britannique de l''océan)')
,('ID','Indonésie')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('IR','Iran')
,('IQ','Iraq')
,('IE','Irlande')
,('IS','Islande')
,('IL','Israël')
,('IT','Italie')
,('JM','Jamaïque')
,('JP','Japon')
,('JE','Jersey')
,('JO','Jordanie')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('KZ','Kazakhstan')
,('KE','Kenya')
,('KG','Kirghizistan')
,('KI','Kiribati')
,('KW','Koweït')
,('LA','Lao')
,('LS','Lesotho')
,('LV','Lettonie')
,('LB','Liban')
,('LR','Libéria')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('LY','Libye')
,('LI','Liechtenstein')
,('LT','Lituanie')
,('LU','Luxembourg')
,('MO','Macao')
,('MK','Macédoine')
,('MG','Madagascar')
,('MY','Malaisie')
,('MW','Malawi')
,('MV','Maldives')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('ML','Mali')
,('MT','Malte')
,('MP','Mariannes du nord')
,('MA','Maroc')
,('MH','Marshall')
,('MQ','Martinique')
,('MU','Maurice')
,('MR','Mauritanie')
,('YT','Mayotte')
,('MX','Mexique')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('FM','Micronésie')
,('MD','Moldova')
,('MC','Monaco')
,('MN','Mongolie')
,('ME','Monténégro')
,('MS','Montserrat')
,('MZ','Mozambique')
,('MM','Myanmar')
,('NA','Namibie')
,('NR','Nauru')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('NP','Népal')
,('NI','Nicaragua')
,('NE','Niger')
,('NG','Nigéria')
,('NU','Niue')
,('NF','Norfolk')
,('NO','Norvège')
,('NC','Nouvelle-Calédonie')
,('NZ','Nouvelle-Zélande')
,('OM','Oman')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('UG','Ouganda')
,('UZ','Ouzbékistan')
,('PK','Pakistan')
,('PW','Palaos')
,('PS','Palestine')
,('PA','Panama')
,('PG','Papouasie-Nouvelle-Guinée')
,('PY','Paraguay')
,('NL','Pays-Bas')
,('XX','Pays inconnu')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('ZZ','Pays multiples')
,('PE','Pérou')
,('PH','Philippines')
,('PN','Pitcairn')
,('PL','Pologne')
,('PF','Polynésie française')
,('PR','Porto Rico')
,('PT','Portugal')
,('QA','Qatar')
,('SY','République arabe syrienne')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('CF','République centrafricaine')
,('RE','Réunion')
,('RO','Roumanie')
,('GB','Royaume-Uni de Grande-Bretagne et d''Irlande d')
,('RU','Russie')
,('RW','Rwanda')
,('EH','Sahara occidental')
,('BL','Saint-Barthélemy')
,('KN','Saint-Kitts-et-Nevis')
,('SM','Saint-Marin')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('MF','Saint-Martin (partie française)')
,('SX','Saint-Martin (partie néerlandaise)')
,('PM','Saint-Pierre-et-Miquelon')
,('VA','Saint-Siège')
,('VC','Saint-Vincent-et-les-Grenadines')
,('SH','Sainte-Hélène')
,('LC','Sainte-Lucie')
,('SB','Salomon')
,('WS','Samoa')
,('AS','Samoa américaines')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('ST','Sao Tomé-et-Principe')
,('SN','Sénégal')
,('RS','Serbie')
,('SC','Seychelles')
,('SL','Sierra Leone')
,('SG','Singapour')
,('SK','Slovaquie')
,('SI','Slovénie')
,('SO','Somalie')
,('SD','Soudan')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('SS','Soudan du Sud')
,('LK','Sri Lanka')
,('SE','Suède')
,('CH','Suisse')
,('SR','Suriname')
,('SJ','Svalbard et île Jan Mayen')
,('SZ','Swaziland')
,('TJ','Tadjikistan')
,('TW','Taïwan')
,('TZ','Tanzanie')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('TD','Tchad')
,('CS','Tchécoslovaquie')
,('CZ','Tchèque')
,('TF','Terres australes françaises')
,('TH','Thaïlande')
,('TL','Timor-Leste')
,('TG','Togo')
,('TK','Tokelau')
,('TO','Tonga')
,('TT','Trinité-et-Tobago')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('TN','Tunisie')
,('TM','Turkménistan')
,('TC','Turks-et-Caïcos (Îles)')
,('TR','Turquie')
,('TV','Tuvalu')
,('UA','Ukraine')
,('SU','URSS')
,('UY','Uruguay')
,('VU','Vanuatu')
,('VE','Venezuela (République bolivarienne du)')
;
INSERT INTO tp_devis.pays (code_pays,libelle) VALUES 
('VN','Viet Nam')
,('VD','Viet Nam (Sud)')
,('WF','Wallis et Futuna')
,('YE','Yémen')
,('YU','Yougoslavie')
,('ZR','Zaïre')
,('ZM','Zambie')
,('ZW','Zimbabwe')
;